NaccNig/Controllers/PostsController.cs
using NaccNig.Models;
using NaccNig.Models.BlogPost;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web.Mvc;

namespace NaccNig.Controllers
{
    public class PostsController : Controller
    {
        private const int PostPerPage = 3;
        private const int PostPerFeed = 25;
        private NaccNigDbContext _db;
        public PostsController()
        {
            _db = new NaccNigDbContext();
        }
        // GET: Posts
        public ActionResult Index(int? id, string category)
        {
            int pageNumber = id ?? 0;
            var items = (from post in _db.Post
                         where post.Title.Contains(category.ToUpper())
                         select post);

            //if (!String.IsNullOrEmpty(category))
            //{
            //    items = items.Where(s => s.Title.ToUpper().Contains(category.ToUpper()));
            //}
            if (String.IsNullOrEmpty(category))
            {
                IEnumerable<Post> posts = (from post in _db.Post
                                           where post.DateTime < DateTime.Now
                                           orderby post.DateTime descending
                                           select post).Skip(pageNumber * PostPerPage)
                                  .Take(PostPerPage + 1);

                ViewBag.IsPreviousLinkVisible = pageNumber > 0;
                ViewBag.IsNextLinkVisible = posts.Count() > PostPerPage;
                ViewBag.PageNumber = pageNumber;
                ViewBag.IsAdmin = IsAdmin;

                return View(posts.Take(PostPerPage));
            }
            return View(items);
        }

        [ValidateInput(false)]
        public ActionResult Update(int? id, string title, string body, DateTime dateTime, string tag)
        {
            //if (!IsAdmin)
            //{
            //    return RedirectToAction("Index");
            //}

            Post post = GetPost(id);
            post.Title = title;
            post.Body = body;
            post.DateTime = dateTime;
            post.Tags.Clear();

            tag = tag ?? string.Empty;
            string[] tagNames = tag.Split(new char[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);
            foreach (string tagName in tagNames)
            {
                post.Tags.Add(GetTag(tagName));
            }

            if (!id.HasValue)
            {
                _db.Post.Add(post);
                //model.AddToPost(post);
            }
            _db.SaveChanges();
            return RedirectToAction("Details", new { id = post.ID });
        }

        private Tag GetTag(string tagName)
        {
            return _db.Tag.FirstOrDefault(x => x.Name == tagName) ?? new Tag() { Name = tagName };
        }

        private Post GetPost(int? id)
        {
            return id.HasValue ? _db.Post.First(x => x.ID == id) : new Post() { ID = -1 };
        }

        public bool IsAdmin { get { return Session["IsAdmin"] != null && (bool)Session["IsAdmin"]; } }
        //public bool IsAdmin { get { return true;/* Session["IsAdmin"] != null && (bool)Session["IsAdmin"];*/ } }

        // GET: Posts/Edit/5
        public ActionResult Edit(int? id)
        {
            Post post = GetPost(id);
            StringBuilder tagList = new StringBuilder();
            foreach (Tag tag in post.Tags)
            {
                tagList.AppendFormat("{0} ", tag.Name);
            }

            ViewBag.Tags = tagList.ToString();
            return View(post);
        }

        public ActionResult Details(int id, string category)
        {
            if (!String.IsNullOrEmpty(category))
            {
                //var items = from i in model.Posts
                //            where i.Title.Contains(category.ToUpper())
                //            select i;
                var items = _db.Post.FirstOrDefault(i => i.Title.ToUpper().Contains(category.ToUpper()));

                return View(items);
            }

            Post post = GetPost(id);
            ViewBag.IsAdmin = IsAdmin;
            return View(post);
        }
        [Authorize]
        [ValidateInput(false)]
        public ActionResult Comment(int id, string name, string email, string body)
        {
            Post post = GetPost(id);
            Comment comment = new Comment();
            comment.Post = post;
            comment.DateTime = DateTime.Now;
            comment.Name = name;
            comment.Email = email;
            comment.Body = body;

            _db.Comment.Add(comment);
            _db.SaveChanges();

            return RedirectToAction("Details", new { id = id });
        }

        public ActionResult Delete(int id)
        {
            //if (IsAdmin)
            //{
            Post post = GetPost(id);
            _db.Post.Remove(post);
            _db.SaveChanges();
            //}

            return RedirectToAction("Index");
        }
        [Authorize]
        public ActionResult DeleteComment(int id)
        {
            if (IsAdmin)
            {
                // Comment comment = model.Comments.Where(x => x.ID == id).First();
                Comment comment = _db.Comment.First(x => x.PostID == id);
                _db.Comment.Remove(comment);
                _db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        public ActionResult Tags(string id)
        {
            Tag tag = GetTag(id);
            ViewBag.IsAdmin = IsAdmin;
            return View("index", tag.Posts);
        }

        //public ActionResult RSS()
        //{
        //    IEnumerable<SyndicationItem> posts =
        //        (from post in _db.Posts
        //         where post.DateTime < DateTime.Now
        //         orderby post.DateTime descending
        //         select post).Take(PostPerFeed).ToList().Select(x => GetSyndicationItem(x));

        //    SyndicationFeed feed = new SyndicationFeed("HeritageTv", "HeritageTv blog", new Uri("http://localhost:60210/"), posts);
        //    Rss20FeedFormatter formattedFeed = new Rss20FeedFormatter(feed);
        //    return new FeedResult(formattedFeed);
        //}

        //private SyndicationItem GetSyndicationItem(Post post)
        //{
        //    return new SyndicationItem(post.Title, post.Body, new Uri("http://localhost:60210/posts/details" + post.ID));
        //}

        public ActionResult Create(int? id)
        {
            Post post = GetPost(id);
            StringBuilder tagList = new StringBuilder();
            foreach (Tag tag in post.Tags)
            {
                tagList.AppendFormat("{0} ", tag.Name);
            }

            ViewBag.Tags = tagList.ToString();
            return View(post);
        }

        [ValidateInput(false)]
        public ActionResult CreatePost(int? id, string title, string body, DateTime dateTime, string tag)
        {
            //    if (!IsAdmin)
            //    {
            //        return RedirectToAction("Index");
            //    }

            Post post = GetPost(id);
            post.Title = title;
            post.Body = body;
            post.DateTime = dateTime;
            post.Tags.Clear();

            tag = tag ?? string.Empty;
            string[] tagNames = tag.Split(new char[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);
            foreach (string tagName in tagNames)
            {
                post.Tags.Add(GetTag(tagName));
            }

            if (!id.HasValue)
            {
                _db.Post.Add(post);
                //model.AddToPost(post);
            }
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public PartialViewResult Menu()
        {
            IEnumerable<string> categories = _db.Post.Select(s => s.Title)
                                                            .OrderByDescending(s => s)
                                                            .Take(5);
            return PartialView(categories);
        }
    }
}

NaccNig/Views/Shared/DashboardLayout.cshtml
@using Microsoft.AspNet.Identity
@using NaccNig.Models
@using NaccNigModels.Members
@using NaccNigModels.Structures

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>

    <link href="~/Content/Dashboard/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/Dashboard/css/datepicker3.css" rel="stylesheet">
    <link href="~/Content/Dashboard/css/styles.css" rel="stylesheet">
    <link href="~/Content/Default/pace.css" rel="stylesheet" />
    <!--Icons-->
    <script src="~/Scripts/Dashboard/lumino.glyphs.js"></script>

    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->

</head>
<body>
    @RenderBody()
    @Html.Partial("_NavBar")
    @Html.Partial("_SideBar")


    <script src="~/Scripts/Dashboard/jquery-1.11.1.min.js"></script>
    <script src="~/Scripts/Dashboard/bootstrap.min.js"></script>
   
    <script src="~/Scripts/Dashboard/bootstrap-datepicker.js"></script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

NaccNig/Views/Shared/Default.cshtml
@using NaccNig.Models
<!DOCTYPE HTML>
<html>
<head>
    <title>@ViewBag.Title</title>

    <!-- BEGIN META -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="your,keywords">
    <meta name="description" content="Short explanation about this website">

    <!-- Main styles for this application-->

    <link href="~/Content/Default/style.css" rel="stylesheet" />
    <link href="~/Content/Default/pace.css" rel="stylesheet" />
    <link href="~/Content/Default/font-awesome.min.css" rel="stylesheet" />
    <!--Icons-->
    <script src="~/Scripts/Dashboard/lumino.glyphs.js"></script>

</head>
<body>
    <br />
    <div class="container body-content">
        
        
               @if (Request.IsAuthenticated)
               {


                if (User.IsInRole(RoleName.Admin))
                {
                <a class="btn-sm btn-default" href="@Url.Action("Dashboard", "Home")">Back To Dashboard</a>
                }
                else
                {
           <a class="btn-sm btn-default"  href="@Url.Action("Dashboard", "ActiveMembers")">Back To Dashboard</a>
                }
                <a class="btn-sm btn-default"  href="@Url.Action("Index", "Home")">Back To Homepage</a>
               }
            
               

        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - NACC Nigeria</p>
        </footer>
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)


        <!-- Bootstrap and necessary plugins-->

        <script src="~/Scripts/jquery-3.3.1.min.js"></script>
        <script src="~/Scripts/bootstrap.min.js"></script>
    </div>
</body>
</html>

NaccNig/Views/Shared/LandingPage.cshtml
@using NaccNig.Models
<!DOCTYPE html>
<html lang="zxx">
<head>
    <title>@ViewBag.Title</title>
    <!--meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="Sweet Home Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script type="application/x-javascript">
        addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
               function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!--//meta tags ends here-->
    <!--booststrap-->

    <link href="~/Content/landingpage/css/bootstrap.css" rel="stylesheet" type="text/css" media="all">
    <!--//booststrap end-->
    <!-- font-awesome icons -->
    <link rel="stylesheet" href="~/Content/landingpage/css/font-awesome.min.css" />

    <!-- //font-awesome icons -->
    <!--stylesheets-->
    <link href="~/Content/landingpage/css/style.css" rel='stylesheet' type='text/css' media="all">
    <link href="~/Content/landingpage/css/popuo-box.css" rel="stylesheet" type="text/css" media="all" /><!-- //pop-ups-->
    <link href="~/Content/landingpage/css/lsb.css" rel="stylesheet" type="text/css"> <!--gallery lsb-->

    <link href="//fonts.googleapis.com/css?family=Montserrat:400,500,600" rel="stylesheet">
    <!--//style sheet end here-->
</head>
<body>
    <div class="header-w3layouts">
        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-fixed-top top-nav-collapse">
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <h3 style="top:0; bottom:auto">
                    <a href="@Url.Action("Index","Home")">
                        <img src="~/images/nacclogo.png" height="60" width="75" /> 
                       <span style="color:white">NACC Plateau</span>
                    </a>
                </h3>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden"><a class="page-scroll" href="#page-top"></a>	</li>
                    @if (Request.IsAuthenticated)
                    {
                        if (User.IsInRole(RoleName.Admin))
                        {
                            <li><a class="" href="@Url.Action("Dashboard","Home")">Dashboard</a></li>
                        }
                        if (User.IsInRole(RoleName.ActiveMember))
                        {
                            <li><a class="" href="@Url.Action("Dashboard","ActiveMembers")">Dashboard</a></li>
                        }
                    }
                    else
                    {
                          <li><a class="page-scroll" href="@Url.Action("Index","Home")">Home</a></li>
                    }
                  
                    <li><a class="page-scroll scroll" href="#about">About</a></li>
                    <li><a class="page-scroll scroll" href="#contact">Contact</a></li>
                            @Html.Partial("loginView")
                    </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>
    </div>
    <!-- //header -->
            @RenderBody()
            <!--footer-->
            <div class="footer">
                <div class="container">
                    <!-- Copyright -->
                    <div class="col-md-7 copyright">
                        <p>© @DateTime.Now.Year  NACC Nigeria. All Rights Reserved | Design by <a href="#" target="_blank"> Sebig Solutions </a></p>

                    </div>
                    <!-- //Copyright -->
                    <div class="col-md-5 bottom-head">
                        <div class="icons-buttn">
                            <ul>
                                <li><a href="#"><span class="fa fa-facebook"></span></a></li>
                                <li><a href="#"><span class="fa fa-twitter"></span></a></li>
                                <li><a href="#"><span class="fa fa-rss"></span></a></li>
                                <li><a href="#"><span class="fa fa-vk"></span></a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="clearfix"> </div>
                </div>
            </div>
            <!--//footer-->
            <!--menu script-->
            <script type='text/javascript' src='~/Content/landingpage/js/jquery-2.2.3.min.js'></script>
            <script type="text/javascript" src="~/Content/landingpage/js/modernizr-2.6.2.min.js"></script>
            <script src="~/Content/landingpage/js/bootstrap.min.js"></script>
            <!--//menu script-->
            <!-- banner-->
            <script src="~/Content/landingpage/js/responsiveslides.min.js"></script>
            <script>
        $(function () {
            $("#slider").responsiveSlides({
                auto: true,
                pager: true,
                nav: true,
                speed: 1000,
                namespace: "callbacks",
                before: function () {
                    $('.events').append("<li>before event fired.</li>");
                },
                after: function () {
                    $('.events').append("<li>after event fired.</li>");
                }
            });
        });
            </script>
            <!-- OnScroll-Number-Increase-JavaScript -->
            <script src="~/Content/landingpage/js/jquery.waypoints.min.js"></script>
            <script src="~/Content/landingpage/js/jquery.countup.js"></script>
            <script>
        $('.counter').countUp();
            </script>
            <!-- //OnScroll-Number-Increase-JavaScript -->
            <!--pop-up-box video-->
            <script src="~/Content/landingpage/js/jquery.magnific-popup.js" type="text/javascript"></script>
            <script>
        $(document).ready(function () {
            $('.popup-with-zoom-anim').magnificPopup({
                type: 'inline',
                fixedContentPos: false,
                fixedBgPos: true,
                overflowY: 'auto',
                closeBtnInside: true,
                preloader: false,
                midClick: true,
                removalDelay: 300,
                mainClass: 'my-mfp-zoom-in'
            });

        });
            </script>
            <!-- //pop-up-box video -->
            <!-- gallery-lightbox -->
            <script src="~/Content/landingpage/js/lsb.min.js"></script>
            <script>
        $(window).load(function () {
            $.fn.lightspeedBox();
        });
            </script>
            <!-- //gallery-lightbox -->
            <!-- start-smoth-scrolling -->
            <script type="text/javascript" src=" ~/Content/landingpage/js/move-top.js"></script>
            <script type="text/javascript" src=" ~/Content/landingpage/js/easing.js"></script>
            <script type="text/javascript">
        jQuery(document).ready(function ($) {
            $(".scroll").click(function (event) {
                event.preventDefault();
                $('html,body').animate({ scrollTop: $(this.hash).offset().top }, 1000);
            });
        });
            </script>
            <!-- start-smoth-scrolling -->
            <!-- for-bottom-to-top smooth scrolling -->
            <script type="text/javascript">
        $(document).ready(function () {
            /*
                var defaults = {
                containerID: 'toTop', // fading element id
                containerHoverID: 'toTopHover', // fading element hover id
                scrollSpeed: 1200,
                easingType: 'linear'
                };
            */
            $().UItoTop({ easingType: 'easeOutQuart' });
        });
            </script>
            <a href="#" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
            <!-- //for-bottom-to-top smooth scrolling -->
    </body>
</html>

NaccNig/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - NACC Nigeria</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("NACC Nigeria", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - NACC Nigeria</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

NaccNig/Views/Shared/_SideBar.cshtml
@using NaccNig.Models

@if (User.IsInRole(RoleName.Admin))
{
<div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
    <form role="search">
        <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
        </div>
    </form>
    <ul class="nav menu">
        <li class="active"><a href="index.html"><svg class="glyph stroked dashboard-dial"><use xlink:href="#stroked-dashboard-dial"></use></svg> Dashboard</a></li>
        <li><a href="@Url.Action("List","User")"><svg class="glyph stroked male-user"><use xlink:href="#stroked-male-user"></use></svg>Manage Members</a></li>
        <li class="parent ">
            <a href="#">
                <span data-toggle="collapse" href="#sub-item-1"><svg class="glyph stroked chevron-down"><use xlink:href="#stroked-chevron-down"></use></svg></span>Manage Posts
            </a>
            <ul class="children collapse" id="sub-item-1">
                <li>
                    <a class="" href="@Url.Action("Index","Posts")">
                        <svg class="glyph stroked email"><use xlink:href="#stroked-email"></use></svg> Blog List
                    </a>
                </li>
                <li>
                    <a class="" href="@Url.Action("Create","Tags")">
                        <svg class="glyph stroked email"><use xlink:href="#stroked-email"></use></svg> Create Category
                    </a>
                </li>
                <li>
                    <a class="" href="@Url.Action("Create","Posts")">
                        <svg class="glyph stroked notepad"><use xlink:href="#stroked-notepad"></use></svg> Create Posts
                    </a>
                </li>

            </ul>

        </li>
        <li class="parent ">
            <a href="#">
                <span data-toggle="collapse" href="#sub-item-2"><svg class="glyph stroked chevron-down"><use xlink:href="#stroked-chevron-down"></use></svg></span>Manage Payment
            </a>
            <ul class="children collapse" id="sub-item-2">
                <li>
                    <a class="" href="@Url.Action("Create","MemberFeeTypes")">
                        <svg class="glyph stroked email"><use xlink:href="#stroked-email"></use></svg> Create Payment Type
                    </a>
                </li>
                <li>
                    <a class="" href="@Url.Action("Index","MemberFeeTypes")">
                        <svg class="glyph stroked email"><use xlink:href="#stroked-email"></use></svg> View Payment List
                    </a>
                </li>
                <li>
                    <a class="" href="@Url.Action("Create","Posts")">
                        <svg class="glyph stroked notepad"><use xlink:href="#stroked-notepad"></use></svg> Create Posts
                    </a>
                </li>

            </ul>
        </li>
        <li class="parent ">
            <a href="#">
                <span data-toggle="collapse" href="#sub-item-2"><svg class="glyph stroked chevron-down"><use xlink:href="#stroked-chevron-down"></use></svg></span>Manage Registration
            </a>
            <ul class="children collapse" id="sub-item-2">
                <li>
                    <a class="" href="@Url.Action("ActiveMemberList","Home")">
                        <svg class="glyph stroked male-user"><use xlink:href="#stroked-male-user"></use></svg> View Active Members
                    </a>
                </li>
                <li>
                    <a class="" href="@Url.Action("PastMemberList","Home")">
                        <svg class="glyph stroked male-user"><use xlink:href="#stroked-male-user"></use></svg> View Past Members
                    </a>
                </li>

            </ul>
        </li>
        <li class="parent ">
            <a href="#">
                <span data-toggle="collapse" href="#sub-item-3"><svg class="glyph stroked chevron-down"><use xlink:href="#stroked-chevron-down"></use></svg></span>Manage Leaders
            </a>
            <ul class="children collapse" id="sub-item-3">
                <li>
                    <a class="" href="@Url.Action("Create","StateExco")">
                        <svg class="glyph stroked male-user"><use xlink:href="#stroked-male-user"></use></svg> State Excos
                    </a>
                </li>
                <li>
                    <a class="" href="@Url.Action("Create","ZonalExco")">
                        <svg class="glyph stroked male-user"><use xlink:href="#stroked-male-user"></use></svg> Zonal Excos
                    </a>
                </li>
                <li>
                    <a class="" href="@Url.Action("Create","Portfolios")">
                        <svg class="glyph stroked male-user"><use xlink:href="#stroked-male-user"></use></svg> Create Positions
                    </a>
                </li>

            </ul>
        </li>

    </ul>
    <div class="attribution">Powered By <a href="#">Sebig Solutions</a></div>
</div>
}

@if (User.IsInRole(RoleName.ActiveMember))
{
    <div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
        <form role="search">
            
        </form>
        <ul class="nav menu">
            <li class="active"><a href="@Url.Action("Dashboard","ActiveMembers")"><svg class="glyph stroked dashboard-dial"><use xlink:href="#stroked-dashboard-dial"></use></svg> Dashboard</a></li>

            <li class="parent ">
                <a href="#">
                    <span data-toggle="collapse" href="#sub-item-1"><svg class="glyph stroked chevron-down"><use xlink:href="#stroked-chevron-down"></use></svg></span> My Account
                </a>
                <ul class="children collapse" id="sub-item-1">
                    <li>
                        <a class="" href="@Url.Action("MakePayment","MembershipFees")">
                            <svg class="glyph stroked chevron-right"><use xlink:href="#stroked-chevron-right"></use></svg> Make Payment
                        </a>
                    </li>
                    <li>
                        <a class="" href="#">
                            <svg class="glyph stroked chevron-right"><use xlink:href="#stroked-chevron-right"></use></svg> Make Donations
                        </a>
                    </li>
                    <li>
                        <a class="" href="#">
                            <svg class="glyph stroked chevron-right"><use xlink:href="#stroked-chevron-right"></use></svg> Check Payment
                        </a>
                    </li>
                </ul>
            </li>

            <li class="parent ">
                <a href="#">
                    <span data-toggle="collapse" href="#sub-item-2"><svg class="glyph stroked chevron-down"><use xlink:href="#stroked-chevron-down"></use></svg></span> Profile
                </a>
                <ul class="children collapse" id="sub-item-2">
                    <li>
                        <a class="" href="@Url.Action("MyProfile","ActiveMembers")">
                            <svg class="glyph stroked chevron-right"><use xlink:href="#stroked-chevron-right"></use></svg> My Profile
                        </a>
                    </li>
                    <li>
                        <a class="" href="@Url.Action("Update","ActiveMembers", new { id= Model.ActiveMemberId})">
                            <svg class="glyph stroked chevron-right"><use xlink:href="#stroked-chevron-right"></use></svg> Update Profile
                        </a>
                    </li>

                </ul>
            </li>

            <li class="parent ">
                <a href="#">
                    <span data-toggle="collapse" href="#sub-item-3"><svg class="glyph stroked chevron-down"><use xlink:href="#stroked-chevron-down"></use></svg></span> Blog
                </a>
                <ul class="children collapse" id="sub-item-3">
                    <li>
                        <a class="" href="@Url.Action("Index","Posts")">
                            <svg class="glyph stroked chevron-right"><use xlink:href="#stroked-chevron-right"></use></svg> BlogPost
                        </a>
                    </li>
                    <li>
                        <a class="" href="@Url.Action("Create","Posts")">
                            <svg class="glyph stroked chevron-right"><use xlink:href="#stroked-chevron-right"></use></svg> Create Blog Posts
                        </a>
                    </li>

                </ul>
            </li>
        </ul>
        <div class="attribution">Powered By <a href="#">Sebig Solutions</a></div>
    </div>
}

NaccNig/Views/Shared/loginView.cshtml
@using Microsoft.AspNet.Identity
@using NaccNig.Models
@if (Request.IsAuthenticated)
{
    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
    {
    @Html.AntiForgeryToken()

    <ul class="nav navbar-nav">
        <li>
            @if (User.IsInRole(RoleName.Admin))
             {
                @Html.ActionLink("Hello " + User.Identity.GetUserName(), "", "")
             }
            @if (User.IsInRole(RoleName.ActiveMember))
             {
                @Html.ActionLink("Hello " + User.Identity.GetUserName(), "MyProfile", "ActiveMembers")
             }
            @if (User.IsInRole(RoleName.PastMember))
            {
                @Html.ActionLink("Hello " + User.Identity.GetUserName(), "MyProfile", "PastMembers")
            }
       
        </li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
    </ul>
    }
}
else
{
    <ul class="nav navbar-nav">
        <li><a class="" href="@Url.Action("Login","Account")">Login</a></li>
        <li><a class="" href="@Url.Action("Register","Account")">Register</a></li>
    </ul>
}