NaccNig/Controllers/ActiveMembersController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using NaccNig.Models;
using NaccNig.ViewModels;
using System.IO;
using System.Collections.Generic;
using NaccNigModels.Members;
using NaccNigModels.Structures;
using NaccNigModels.PopUp;

namespace NaccNig.Controllers
{
    [Authorize(Roles = RoleName.Admin + "," + RoleName.ActiveMember)]

    public class ActiveMembersController : Controller
    {
        private NaccNigDbContext db;

        public ActiveMembersController()
        {
            db = new NaccNigDbContext();
        }

        [Authorize(Roles = RoleName.Admin)]
        // GET: ActiveMembers
        public ActionResult Index()
        {
            return View(db.ActiveMember.ToList());
        }
        public async Task<ActionResult> Dashboard()
        {
            var model = new MemberDashboardVM();
            var userId = User.Identity.GetUserId();
            var activeId = userId;
            var activeUser = await db.ActiveMember.AsNoTracking()
                                     .FirstOrDefaultAsync(a => a.ActiveMemberId.Equals(activeId));
            var stateChapter = StateChapter.GetStateChapters().FirstOrDefault();
            var zone = Zone.GetZones().FirstOrDefault();
           
            if (activeUser == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (activeUser != null)
            {
                model.Firstname = activeUser.Firstname;
                model.Middlename = activeUser.Middlename;
                model.Surname = activeUser.Surname;
                model.Address = activeUser.Address;
                model.CallUpNumber = activeUser.CallUpNumber;
                model.PhoneNumber = activeUser.PhoneNumber;
                model.StateCode = activeUser.StateCode;
                model.StateOfOrigin = activeUser.StateOfOrigin;
                model.Gender = activeUser.Gender;
                model.YearServed = activeUser.DateServed;
                model.ActiveMemberId = activeUser.ActiveMemberId;
                model.Fullname = activeUser.Fullname;
                model.Age = activeUser.Age;
                model.Photo = activeUser.Photo;
                model.StateChapter = stateChapter.StateChapterName;
                model.Zone = zone.ZoneName;
               
            }
            var memberfee = await db.MemberFeeType.Include(m=>m.MembershipFee).AsNoTracking().ToListAsync();
            
            ViewBag.MemberFee = memberfee;

               
            var myPix = model.Photo;
           
            ViewBag.Photo = myPix;
           
            return View(model);
        }
        // GET: ActiveMembers/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ActiveMember activeMember = db.ActiveMember.Find(id);
            if (activeMember == null)
            {
                return HttpNotFound();
            }
            return View(activeMember);
        }

        // GET: ActiveMembers/Edit/5
        [AllowAnonymous]
        public ActionResult ProfileUpdate()
        {
            
            var myGender = from Gender s in Enum.GetValues(typeof(Gender))
                           select new { ID = s, Name = s.ToString() };
            var myState = from State s in Enum.GetValues(typeof(State))
                          select new { ID = s, Name = s.ToString() };
            var depState = from StateDeployed s in Enum.GetValues(typeof(StateDeployed))
                           select new { ID = s, Name = s.ToString() };
            ViewBag.Gender = new SelectList(myGender, "Name", "Name");
            ViewBag.StateOfOrigin = new SelectList(myState, "Name", "Name");
            ViewBag.StateOfDeployment = new SelectList(depState, "Name", "Name");
            ViewBag.StateList = new SelectList(StateChapter.GetStateChapters(), "StateChapId", "StateChapterName");

            return View();
        }

        // POST: ActiveMembers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ProfileUpdate(ActiveMember activeMember)
        {
            var userId = User.Identity.GetUserId();
            activeMember.ActiveMemberId = userId;


            if (ModelState.IsValid)
            {
                var fileName = Path.GetFileNameWithoutExtension(activeMember.ImageFile.FileName);
                var extension = Path.GetExtension(activeMember.ImageFile.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                activeMember.Photo = "~/PhotoUpload/ActiveMembers/" + fileName;
                fileName = Path.Combine(Server.MapPath("~/PhotoUpload/ActiveMembers/"), fileName);
                activeMember.ImageFile.SaveAs(fileName);
                db.ActiveMember.Add(activeMember);
                await db.SaveChangesAsync();
                return RedirectToAction("Dashboard");
            }
            var myGender = from Gender s in Enum.GetValues(typeof(Gender))
                           select new { ID = s, Name = s.ToString() };
            var myState = from State s in Enum.GetValues(typeof(State))
                          select new { ID = s, Name = s.ToString() };
            var depState = from StateDeployed s in Enum.GetValues(typeof(StateDeployed))
                           select new { ID = s, Name = s.ToString() };
            ViewBag.Gender = new SelectList(myGender, "Name", "Name");
            ViewBag.StateOfOrigin = new SelectList(myState, "Name", "Name");
            ViewBag.StateOfDeployment = new SelectList(depState, "Name", "Name");
            ViewBag.StateList = new SelectList(StateChapter.GetStateChapters(), "StateChapId", "StateChapterName");
            return View(activeMember);
        }
        [Authorize]
        public async Task<ActionResult> MyProfile(MyProfileVM model)
        {
            var userId = User.Identity.GetUserId();
            var activeId = userId;
            var activeUser = await db.ActiveMember.AsNoTracking()
                                     .FirstOrDefaultAsync(a => a.ActiveMemberId.Equals(activeId));
  
            if (activeUser != null)
            {
                model.Firstname = activeUser.Firstname;
                model.Middlename = activeUser.Middlename;
                model.Surname = activeUser.Surname;
                model.Address = activeUser.Address;
                model.CallUpNumber = activeUser.CallUpNumber;
                model.PhoneNumber = activeUser.PhoneNumber;
                model.StateCode = activeUser.StateCode;
                model.StateOfOrigin = activeUser.StateOfOrigin;
                model.Gender = activeUser.Gender;
                model.ActiveMemberId = activeUser.ActiveMemberId;
                model.Fullname = activeUser.Fullname;
                model.Age = activeUser.Age;
                model.ActiveMemberId = activeUser.ActiveMemberId;
                model.Photo = activeUser.Photo;
               
                model.StateChapter = activeUser.StateChapterId;
                model.Zone = activeUser.ZoneId;

            }
            var pic = model.Photo;
            ViewBag.Photo = pic;
            return View(model);
        }

        // GET: ActiveMembers/Edit/5
        
        [HttpGet]
        public ActionResult Update(string id)
        {
                    
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ActiveMember activeMember = db.ActiveMember.Find(id);
            if (activeMember == null)
            {
                return HttpNotFound();
            }

            var myGender = from Gender s in Enum.GetValues(typeof(Gender))
                           select new { ID = s, Name = s.ToString() };
            var myState = from State s in Enum.GetValues(typeof(State))
                          select new { ID = s, Name = s.ToString() };
            var depState = from StateDeployed s in Enum.GetValues(typeof(StateDeployed))
                           select new { ID = s, Name = s.ToString() };
            ViewBag.Gender = new SelectList(myGender, "Name", "Name");
            ViewBag.StateOfOrigin = new SelectList(myState, "Name", "Name");
            ViewBag.StateOfDeployment = new SelectList(depState, "Name", "Name");
            ViewBag.StateList = new SelectList(StateChapter.GetStateChapters(), "StateChapId", "StateChapterName");
            ViewBag.Zone = new SelectList(Zone.GetZones(), "ZId", "ZoneName");
            return View(activeMember);
        }

        // POST: ActiveMembers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Update(ActiveMember activeMember)
        {
            var userId = User.Identity.GetUserId();
            activeMember.ActiveMemberId = userId;

     

            if (ModelState.IsValid)
            {
                var fileName = Path.GetFileNameWithoutExtension(activeMember.ImageFile.FileName);
                var extension = Path.GetExtension(activeMember.ImageFile.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                activeMember.Photo = "~/PhotoUpload/ActiveMembers/" + fileName;

NaccNig/Views/ActiveMembers/Create.cshtml
@model NaccNigModels.Members.ActiveMember

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/DashboardLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ActiveMember</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ActiveMemberId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ActiveMemberId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ActiveMemberId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StateOfDeployment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StateOfDeployment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StateOfDeployment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StateCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StateCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StateCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CallUpNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CallUpNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CallUpNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Firstname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Firstname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Firstname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Middlename, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Middlename, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Middlename, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Dob, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Dob, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Dob, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StateOfOrigin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StateOfOrigin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StateOfOrigin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Photo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

NaccNig/Views/ActiveMembers/MakePayment.cshtml
@model NaccNig.ViewModels.PaymentVM

@{
    ViewBag.Title = "Make Payment";
    Layout = "~/Views/Shared/DashboardLayout.cshtml";
   
}
<div id="content">
    <section>
        <div class="section-body">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">

                    <div style="display:none" class="redirect-message">
                        <div>
                            <p><img src="@Url.Content("~/Content/loading.gif")" alt="Alternate Text" /> </p>
                            <p>Please wait..</p>
                            <p>You are been redirected to a secure payment system</p>
                        </div>
                    </div>
                    <div style="margin-top:40px" class="container">
                        <div class="form-group">
                            <p class="text-left">
                               
                                <span><img src="@Url.Content(Model.Photo)" height="50" width="50"/></span>
                            </p>
                        </div>

                        <div class="row">
                            <div class="col-md-8">
                                <div class="form-group">
                                    <strong class="text-left">
                                        <b>Payment ID:</b>
                                        <span>@Model.PaymentId</span>
                                    </strong>
                                </div>
                                <div class="form-group">
                                    <p class="text-left">
                                        <b>Member Name:</b>
                                        <span>@Model.MemberName</span>
                                    </p>
                                </div>
                                <div class="form-group">
                                    <p class="text-left">
                                        <b>Payment Category:</b>
                                        <span>@Model.CategoryName</span>
                                    </p>
                                </div>
                                <div class="form-group">
                                    <p class="text-left">
                                        <b>Amount:</b>
                                        <span># @Model.Amount</span>
                                    </p>
                                </div>
                                        <div class="form-group">
                                            <a id="payNowButton" href="@Url.Action("InitializePayment", "ActiveMembers")" class="btn btn-success payNowBtn">
                                                Pay Now <span class="glyphicon glyphicon-play"></span>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                    </div>
                
        </section>
    </div>

@section Scripts{
       <script type="text/javascript">

        $(function () {
          function InitTransaction(data) {
            return $.ajax({
                type: "POST",
                url: "@Url.Action("InitializePayment", "ActiveMembers")",
                    data: data,
                    dataType: 'json',
                    contentType: 'application/json;charset=utf-8'
            });
           }

          $("#payNowButton").click(function (e) {
              $(".redirect-message").show();
              e.preventDefault();
              var amnt =parseInt((parseInt($(this).attr("href")) * 100));

            var data = JSON.stringify({
                firstName: $("#PaymentCategoryId").val(),
                lastName: $("#AmountId").val(),
                email: $("#").val(),
                phone: $("#phone").val(),
                amount: amnt
              });



            $.when(InitTransaction(data)).then(function (response) {


                if (response.error == false) {

                    window.location.href = response.result.data.authorization_url;
                } else {
                    $(".redirect-message").hide();
                }

            }).fail(function () {
                $(".redirect-message").hide()
                });

        });

    });
 </script>
}

NaccNig/Views/ActiveMembers/ProfileUpdate.cshtml
@using Microsoft.AspNet.Identity
@model NaccNigModels.Members.ActiveMember

@{
    /**/

    ViewBag.Title = "Profile Update";
    Layout = "~/Views/Shared/Default.cshtml";

}
@section Scripts{
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {

            $.get("/ActiveMembers/GetStateChapterList/", function (data) {
                var items = "<option>---- State Chapter ----</option>";
                $.each(data, function (index, row) {
                    items += " <option value='" + row.StateChapId + "'>" + row.StateChapterName + "</option>";
                    $("#StateChapterId").html(items);
                    //$("#StateChapterId").append(" <option value='" + row.StateChapId + "'>" + row.StateChapterName + "</option>")
                });
            });
            $("#StateChapterId").change(function () {
                $.get("/ActiveMembers/GetZoneList/", { StateChapId: $("#StateChapterId").val() }, function (data) {
                    var items = "<option>---- zonal chapters ----</option>";
                    $.each(data, function (index, row) {
                        items += "<option value='" + row.Value + "'>" + row.Text + "</option>";
                        $("#ZoneId").html(items);
                        //$("#ZoneId").append("<option value='" + row.ZId + "'>" + row.ZoneName + "</option>")
                    });
                });
            });
        });
        $(document).ready(function () {

            $("#positionLabel").hide();
            $("#Position").hide();
            $("#DateServedLabel").hide();
            $("#DateServed").hide();



            $("#IsExco").on("click", function (e) {

                $("#positionLabel").slideToggle();
                $("#Position").slideToggle();
                $("#DateServedLabel").slideToggle();
                $("#DateServed").slideToggle();
                e.preventDefault();
            });

        });
    </script>
}

<div class="section-body">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            @using (Html.BeginForm("ProfileUpdate", "ActiveMembers", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">

                    <hr />


                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                    <div class="form-group">
                        @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
                        <input type="file" name="ImageFile" value="" />
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Firstname, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Firstname, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Firstname, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Middlename, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Middlename, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Middlename, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("Gender", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Dob, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Dob, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Dob, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.StateOfOrigin, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("StateOfOrigin", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.StateOfOrigin, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <div class="form-group">
                        @Html.LabelFor(model => model.StateChapterId, "State Chapter", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.StateChapterId, ViewBag.StateList as SelectList, "Select State Chapter", htmlAttributes: new { id = "StateChapterId", @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.StateChapterId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ZoneId, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.ZoneId, new SelectList(" "), "Select Zonal Chapter", htmlAttributes: new { id = "ZoneId", @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.ZoneId, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <div class="form-group">
                        @Html.LabelFor(model => model.IsExco, "Are you An Exco?", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.CheckBoxFor(model => model.IsExco)
                            @Html.ValidationMessageFor(model => model.IsExco, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Position, htmlAttributes: new { id = "positionLabel", @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Position, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.DateServed, "Year of Service", htmlAttributes: new { id = "DateServedLabel", @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.DateServed, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DateServed, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <div class="form-group">
                        @Html.LabelFor(model => model.StateCode, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.StateCode, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.StateCode, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.CallUpNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.CallUpNumber, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.CallUpNumber, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Update" class="btn btn-info" />
                        </div>
                    </div>
                </div>
            }



        </div>
    </div>

</div>