NaccNig/Controllers/ZonalExcoController.cs
using System;
using Microsoft.AspNet.Identity;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NaccNig.Models;
using NaccNigModels.Executives;
using NaccNig.ViewModels;

namespace NaccNig.Controllers
{
    public class ZonalExcoController : Controller
    {
        private NaccNigDbContext db = new NaccNigDbContext();

        // GET: ZonalExco
        public ActionResult Index()
        {
            var zonalExco = db.ZonalExco.Include(z => z.ActiveMember).Include(z => z.Portfolio);
            return View(zonalExco.ToList());
        }

        // GET: ZonalExco/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ZonalExco zonalExco = db.ZonalExco.Find(id);
            if (zonalExco == null)
            {
                return HttpNotFound();
            }
            return View(zonalExco);
        }

        // GET: ZonalExco/Create
        public ActionResult Create()
        {
            ViewBag.ActiveMemberId = new SelectList(db.ActiveMember, "ActiveMemberId", "Fullname");
            ViewBag.PortfolioId = new SelectList(db.Portfolio, "Id", "PortfolioName");
            ViewBag.ZoneId = new SelectList(db.ZonalChapter, "Id", "ZoneName");
            return View();
        }

        // POST: ZonalExco/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ZonalExco zonalExco)
        {
            if (ModelState.IsValid)
            {
                db.ZonalExco.Add(zonalExco);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ActiveMemberId = new SelectList(db.ActiveMember, "ActiveMemberId", "Fullname", zonalExco.ActiveMemberId);
            ViewBag.PortfolioId = new SelectList(db.Portfolio, "Id", "PortfolioName", zonalExco.PortfolioId);
            ViewBag.ZoneId = new SelectList(db.ZonalChapter, "Id", "ZoneName", zonalExco.ZoneId);
            return View(zonalExco);
        }

        public ActionResult GetZone()
        {
            var zoneList = db.ZonalChapter.AsNoTracking().ToList();
            return View(zoneList);
        }
    
        

        public ActionResult ZonalExecutives(int? id)
        {
            var zonalChapter = db.ZonalExco.Include(x=>x.ZonalChapter).AsNoTracking().Where(x => x.ZoneId == id).ToList();
            return View(zonalChapter);
        }
        public ActionResult ExecutiveDetails(int? id)
        {
            StateExcoDetailVM model = new StateExcoDetailVM();
            var excoDetail = db.ZonalExco.Include(s => s.ActiveMember)
                                         .Include(s => s.Portfolio)
                                         .AsNoTracking()
                                        .FirstOrDefault(e => e.ZonalExcoId == id);

            if (excoDetail != null)
            {
                model.Fullname = excoDetail.ActiveMember.Fullname;
                model.StateCode = excoDetail.ActiveMember.StateCode;
                model.Gender = excoDetail.ActiveMember.Gender;
                model.Photo = excoDetail.ActiveMember.Photo;
                model.StateOfOrigin = excoDetail.ActiveMember.StateOfOrigin;
                model.Address = excoDetail.ActiveMember.Address;
                model.PortfolioName = excoDetail.Portfolio.PortfolioName;
                model.ChapterName = ViewBag.State;
                model.ZoneName = ViewBag.Zones;
                model.PhoneNumber = excoDetail.ActiveMember.PhoneNumber;
                model.ZoneId = excoDetail.ZoneId;
            }
            return View(model);
        }

        // GET: ZonalExco/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ZonalExco zonalExco = db.ZonalExco.Find(id);
            if (zonalExco == null)
            {
                return HttpNotFound();
            }
            ViewBag.ActiveMemberId = new SelectList(db.ActiveMember, "ActiveMemberId", "Fullname", zonalExco.ActiveMemberId);
            ViewBag.PortfolioId = new SelectList(db.Portfolio, "Id", "PortfolioName", zonalExco.PortfolioId);
            ViewBag.ZoneId = new SelectList(db.ZonalChapter, "Id", "ZoneName", zonalExco.ZoneId);
            return View(zonalExco);
        }

        // POST: ZonalExco/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ZonalExco zonalExco)
        {
            if (ModelState.IsValid)
            {
                db.Entry(zonalExco).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ActiveMemberId = new SelectList(db.ActiveMember, "ActiveMemberId", "Fullname", zonalExco.ActiveMemberId);
            ViewBag.PortfolioId = new SelectList(db.Portfolio, "Id", "PortfolioName", zonalExco.PortfolioId);
            ViewBag.ZoneId = new SelectList(db.ZonalChapter, "Id", "ZoneName", zonalExco.ZoneId);
            return View(zonalExco);
        }

        // GET: ZonalExco/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ZonalExco zonalExco = db.ZonalExco.Find(id);
            if (zonalExco == null)
            {
                return HttpNotFound();
            }
            return View(zonalExco);
        }

        // POST: ZonalExco/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ZonalExco zonalExco = db.ZonalExco.Find(id);
            db.ZonalExco.Remove(zonalExco);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NaccNig/Views/ZonalExco/Create.cshtml
@model NaccNigModels.Executives.ZonalExco

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/Default.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ZonalExco</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ZonalExcoId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ZonalExcoId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ZonalExcoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ZoneId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ZoneId",null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ZoneId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PortfolioId, "PortfolioId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PortfolioId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PortfolioId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ActiveMemberId, "ActiveMemberId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ActiveMemberId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ActiveMemberId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

NaccNig/Views/ZonalExco/Delete.cshtml
@model NaccNigModels.Executives.ZonalExco

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/Default.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ZonalExco</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ActiveMember.StateCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActiveMember.StateCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Portfolio.PortfolioName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Portfolio.PortfolioName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ZonalExcoId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ZonalExcoId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ZoneId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ZoneId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

NaccNig/Views/ZonalExco/Details.cshtml
@model NaccNigModels.Executives.ZonalExco

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/Default.cshtml";
}

<h2>Details</h2>

<div>
    <h4>ZonalExco</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ActiveMember.StateCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActiveMember.StateCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Portfolio.PortfolioName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Portfolio.PortfolioName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ZonalExcoId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ZonalExcoId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ZoneId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ZoneId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

NaccNig/Views/ZonalExco/Edit.cshtml
@model NaccNigModels.Executives.ZonalExco

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/Default.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ZonalExco</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.ZonalExcoId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ZonalExcoId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ZonalExcoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ZoneId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ZoneId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ZoneId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PortfolioId, "PortfolioId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PortfolioId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PortfolioId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ActiveMemberId, "ActiveMemberId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ActiveMemberId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ActiveMemberId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

NaccNig/Views/ZonalExco/ExecutiveDetails.cshtml
@{
    ViewBag.Title = "ExecutiveDetails";
    Layout = "~/Views/Shared/Default.cshtml";
}

<div class="row">
    <div class="col-md-6 offset-3">
        <div class="jumbotron" style="background-color:lightgray">
            <p style="float:right" class="btn-sm btn-info"><a href="@Url.Action("ZonalExecutives", "ZonalExco", new {id = Model.ZoneId})">Back</a></p>

            @if (Model.Photo != null)
            {
                <p>
                    <img src="@Url.Content(Model.Photo)" class="img-rounded" height="100" width="100" />
                </p>
            }
            <p>
                <b>Full Name </b>: @Model.Fullname
            </p>
            <p>
                <b> Portfolio</b>: @Model.PortfolioName
            </p>
            <p>
                <b> Contact</b>: @Model.PhoneNumber
            </p>
            <p>
                <b>State Code </b>: @Model.StateCode
            </p>
            <p>
                <b>State Of Origin</b>: @Model.StateOfOrigin
            </p>
            <p>
                <b>Gender</b> : @Model.Gender
            </p>
            <p>
                <b>Address</b>: @Model.Address
            </p>
        </div>
    </div>
</div>

NaccNig/Views/ZonalExco/GetZone.cshtml
@model IEnumerable<NaccNigModels.Executives.ZonalChapter>

@{
    ViewBag.Title = "GetZone";
    Layout = "~/Views/Shared/Default.cshtml";
}

<h2>Get Zone</h2>

<div class="row">
    <div class="col-md-8 offset-2">
        <table class="table table-hover">
            <tr>
                <th>#</th>
                <th>Zonal Name </th>
                <th></th>
            </tr>
            @foreach(var item in Model)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.ZoneName</td>
                    <td><a class="btn btn-primary" href="@Url.Action("ZonalExecutives","ZonalExco",
                       new {id = item.Id})">View Executives</a></td>
                </tr>
            }
        </table>
    </div>
</div>

NaccNig/Views/ZonalExco/Index.cshtml
@model IEnumerable<NaccNigModels.Executives.ZonalExco>

@{
    ViewBag.Title = "Index";    
    Layout = "~/Views/Shared/Default.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ActiveMember.Fullname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Portfolio.PortfolioName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ZonalExcoId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ZoneId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ActiveMember.Fullname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Portfolio.PortfolioName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ZonalExcoId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ZoneId)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

NaccNig/Views/ZonalExco/ZonalExecutives.cshtml
@model IEnumerable<NaccNigModels.Executives.ZonalExco>
@using NaccNig.Models

@{
    ViewBag.Title = "ZonalExcecutives";
    Layout = "~/Views/Shared/Default.cshtml";
}

@if (User.IsInRole(RoleName.Admin))
{
    <h2>ZonalExcecutives</h2>

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ActiveMember.Fullname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Portfolio.PortfolioName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ZonalChapter.ZoneName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ZoneId)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ActiveMember.Fullname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Portfolio.PortfolioName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ZonalExcoId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ZonalChapter.ZoneName)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }

    </table>
}

@if (User.IsInRole(RoleName.ActiveMember))
{
    <div class="row">
        <div class="col-md-10 offset-1">

       
            <table class="table table-hover">
                <tr>
                    <th>Photo</th>
                    <th>Fullname</th>
                    <th>Position</th>
                    <th>State Code</th>
                    <th>Gender</th>
                    <th>Phone Number</th>
                    <th></th>
                </tr>
                @foreach (var item in Model)
                {
                    <p class="text-left">@item.ZonalChapter.ZoneName Executives</p>
                    <tr>
                       
                        <td><img src="@Url.Content(item.ActiveMember.Photo)" width="30" height="30" class="img-circle"/></td>
                        <td>@item.ActiveMember.Fullname</td>
                        <td>@item.Portfolio.PortfolioName</td>
                        <td>@item.ActiveMember.StateCode</td>
                        <td>@item.ActiveMember.Gender</td>
                        <td>@item.ActiveMember.PhoneNumber</td>
                        <td>
                            <a class="btn btn-primary" href="@Url.Action("ExecutiveDetails","ZonalExco",
                       new {id = item.ZonalExcoId})">View Detail</a>
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>
}