NaccNig/Controllers/StateExcoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using NaccNig.Models;
using NaccNig.ViewModels;
using NaccNigModels.Executives;
using NaccNigModels.Structures;

namespace NaccNig.Controllers
{
    public class StateExcoController : Controller
    {
        private NaccNigDbContext db = new NaccNigDbContext();

        // GET: StateExco
        public ActionResult Index()
        {
            var stateExco = db.StateExco.Include(s => s.ActiveMember).Include(s => s.Portfolio);
            return View(stateExco.ToList());
        }

        // GET: StateExco/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StateExco stateExco = db.StateExco.Find(id);
            if (stateExco == null)
            {
                return HttpNotFound();
            }
            return View(stateExco);
        }


        public ActionResult StateExecutives()
        {
            var excoState = db.StateExco.Include(s => s.ActiveMember).Include(s => s.Portfolio).ToList();
            
            return View(excoState);
        }
        public ActionResult StateExcoDetail(int? id)
        {
            StateExcoDetailVM model = new StateExcoDetailVM();
            var excoDetail = db.StateExco.Include(s => s.ActiveMember)
                                         .Include(s => s.Portfolio)
                                         .AsNoTracking()
                                        .FirstOrDefault(e=>e.StateExcoId == id);

            if(excoDetail != null)
            {
                model.Fullname = excoDetail.ActiveMember.Fullname;
                model.StateCode = excoDetail.ActiveMember.StateCode;
                model.Gender = excoDetail.ActiveMember.Gender;
                model.Photo = excoDetail.ActiveMember.Photo;
                model.StateOfOrigin = excoDetail.ActiveMember.StateOfOrigin;
                model.Address = excoDetail.ActiveMember.Address;
                model.PortfolioName = excoDetail.Portfolio.PortfolioName;
                model.ChapterName = ViewBag.State;
                model.ZoneName = ViewBag.Zones;
                model.PhoneNumber = excoDetail.ActiveMember.PhoneNumber;
            }
            return View(model);

        }

        // GET: StateExco/Create
        public ActionResult Create()
        {
            ViewBag.ActiveMemberId = new SelectList(db.ActiveMember, "ActiveMemberId", "Fullname");
            ViewBag.PortfolioId = new SelectList(db.Portfolio, "Id", "PortfolioName");
            return View();
        }

        // POST: StateExco/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,StateExcoId,PortfolioId,ActiveMemberId")] StateExco stateExco)
        {
            if (ModelState.IsValid)
            {
                db.StateExco.Add(stateExco);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ActiveMemberId = new SelectList(db.ActiveMember, "ActiveMemberId", "Fullname", stateExco.ActiveMemberId);
            ViewBag.PortfolioId = new SelectList(db.Portfolio, "Id", "PortfolioName", stateExco.PortfolioId);
            return View(stateExco);
        }

        // GET: StateExco/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StateExco stateExco = db.StateExco.Find(id);
            if (stateExco == null)
            {
                return HttpNotFound();
            }
            ViewBag.ActiveMemberId = new SelectList(db.ActiveMember, "ActiveMemberId", "Fullname", stateExco.ActiveMemberId);
            ViewBag.PortfolioId = new SelectList(db.Portfolio, "Id", "PortfolioName", stateExco.PortfolioId);
            return View(stateExco);
        }

        // POST: StateExco/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,StateExcoId,PortfolioId,ActiveMemberId")] StateExco stateExco)
        {
            if (ModelState.IsValid)
            {
                db.Entry(stateExco).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ActiveMemberId = new SelectList(db.ActiveMember, "ActiveMemberId", "Fullname", stateExco.ActiveMemberId);
            ViewBag.PortfolioId = new SelectList(db.Portfolio, "Id", "PortfolioName", stateExco.PortfolioId);
            return View(stateExco);
        }

        // GET: StateExco/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StateExco stateExco = db.StateExco.Find(id);
            if (stateExco == null)
            {
                return HttpNotFound();
            }
            return View(stateExco);
        }

        // POST: StateExco/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            StateExco stateExco = db.StateExco.Find(id);
            db.StateExco.Remove(stateExco);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NaccNig/Views/StateExco/Create.cshtml
@model NaccNigModels.Executives.StateExco

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/Default.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>StateExco</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StateExcoId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StateExcoId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StateExcoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PortfolioId, "PortfolioId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PortfolioId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PortfolioId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ActiveMemberId, "ActiveMemberId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ActiveMemberId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ActiveMemberId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NaccNig/Views/StateExco/Delete.cshtml
@model NaccNigModels.Executives.StateExco

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/Default.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>StateExco</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ActiveMember.StateCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActiveMember.StateCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Portfolio.PortfolioName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Portfolio.PortfolioName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StateExcoId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StateExcoId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

NaccNig/Views/StateExco/Details.cshtml
@model NaccNigModels.Executives.StateExco

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/Default.cshtml";
}

<h2>Details</h2>

<div>
    <h4>StateExco</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ActiveMember.StateCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActiveMember.StateCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Portfolio.PortfolioName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Portfolio.PortfolioName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StateExcoId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StateExcoId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

NaccNig/Views/StateExco/Edit.cshtml
@model NaccNigModels.Executives.StateExco

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/Default.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>StateExco</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.StateExcoId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StateExcoId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StateExcoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PortfolioId, "PortfolioId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PortfolioId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PortfolioId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ActiveMemberId, "ActiveMemberId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ActiveMemberId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ActiveMemberId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NaccNig/Views/StateExco/Index.cshtml
@model IEnumerable<NaccNigModels.Executives.StateExco>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Default.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ActiveMember.Fullname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Portfolio.PortfolioName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StateExcoId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ActiveMember.Fullname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Portfolio.PortfolioName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StateExcoId)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

NaccNig/Views/StateExco/StateExcoDetail.cshtml
@model NaccNig.ViewModels.StateExcoDetailVM
@{
    ViewBag.Title = "StateExcoDetail";
    Layout = "~/Views/Shared/Default.cshtml";
}


<div class="row">
    <div class="col-md-6 offset-3">
        <div class="jumbotron" style="background-color:lightgray">
            <p style="float:right" class="btn-sm btn-info">@Html.ActionLink("Back","StateExecutives", "StateExco")</p>

            @if (Model.Photo != null)
    {
        <p>
            <img src="@Url.Content(Model.Photo)" class="img-rounded" height="100" width="100" />
        </p>
}
            <p>
                <b>Full Name </b>: @Model.Fullname
            </p>
            <p>
                <b> Portfolio</b>: @Model.PortfolioName
            </p>
            <p>
                <b> Contact</b>: @Model.PhoneNumber
            </p>
            <p>
                <b>State Code </b>: @Model.StateCode
            </p>
            <p>
                <b>State Of Origin</b>: @Model.StateOfOrigin
            </p>
            <p>
                <b>Gender</b> : @Model.Gender
            </p>
            <p>
                <b>Address</b>: @Model.Address
            </p>
        </div>
    </div>
</div>

NaccNig/Views/StateExco/StateExecutives.cshtml
@model IEnumerable<NaccNigModels.Executives.StateExco>
@{
    ViewBag.Title = "StateExecutives";
    Layout = "~/Views/Shared/Default.cshtml";
}

<div class="row">
    <table class="table table-hover table-responsive">
        <tr>
            <th>#</th>
            <th>Picture</th>
            <th>Fullname</th>
            <th>State Code</th>
            <th>Phone Number</th>
            <th>Portfolio</th>
            <th>Gender</th>
            <th>State Of Origin</th>
            <th></th>

        </tr>
        @foreach(var person in Model)
        {
        <tr>
            <td>@person.StateExcoId</td>
            <td><img src="@Url.Content(person.ActiveMember.Photo)" class="img-circle" height="50" width="50" /></td>
            <td>@person.ActiveMember.Fullname</td>
            <td>@person.ActiveMember.StateCode</td>
            <td>@person.ActiveMember.PhoneNumber</td>
            <td>@person.Portfolio.PortfolioName</td>
            <td>@person.ActiveMember.Gender</td>
            <td>@person.ActiveMember.StateOfOrigin</td>

            <td><a href="@Url.Action("StateExcoDetail","StateExco", new { id = person.StateExcoId})">View Exco Detail</a></td>
        </tr>
        }
    </table>
</div>